//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentCoding.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContentCoding.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Absolutist
        ///%
        ///absolutely	1
        ///all	1
        ///always	1
        ///complete	1
        ///completely	1
        ///constant	1
        ///constantly	1
        ///definitely	1
        ///entire	1
        ///ever	1
        ///every	1
        ///everyone	1
        ///everything	1
        ///full	1
        ///must	1
        ///never	1
        ///nothing	1
        ///totally	1
        ///whole	1.
        /// </summary>
        internal static string Absolutist_Words {
            get {
                return ResourceManager.GetString("Absolutist_Words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///11	Negative
        ///22	Positive
        ///1	impaired
        ///2	despondent
        ///3	shrew
        ///4	recluse
        ///5	vulnerable
        ///6	golden
        ///7	grandparent
        ///8	conservative
        ///%
        ///active	22	6
        ///adventurous	22	6
        ///affluent	22	6
        ///afraid	11	2	5
        ///alert	22	6
        ///alienated	11	2
        ///alone	11	4
        ///amusing	22	7
        ///annoying	11	3
        ///anxious	11	2	5
        ///approachable	22	6	7
        ///beach	22	6
        ///bitter	11	3
        ///bored	11	2
        ///boring	11	3
        ///bullied	11	5
        ///capable	22	6
        ///car	22	6
        ///cash	22	6
        ///cheerful	22	6
        ///child*	22	7
        ///comfortable	22	6
        ///companionable	22	6	7
        ///complain*	11	3
        ///conservative	22	8
        ///content	22 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Age_Stereotypes_Dictionary {
            get {
                return ResourceManager.GetString("Age_Stereotypes_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Agency
        ///2	Communion
        ///%
        ///able	1
        ///accomplish*	1
        ///accurac*	1
        ///accurate*	1
        ///achiev*	1
        ///acquir*	1
        ///actualiz*	1
        ///adaptab*	1
        ///adept*	1
        ///ambition*	1
        ///ambitious*	1
        ///aptitude*	1
        ///apt*	1
        ///aspir*	1
        ///assert*	1
        ///attain*	1
        ///authoritative*	1
        ///autonom*	1
        ///capab*	1
        ///careful*	1
        ///choice*	1
        ///clever*	1
        ///compet*	1
        ///completion	1
        ///confident*	1
        ///conquer*	1
        ///conscientious*	1
        ///contemplat*	1
        ///contend*	1
        ///contest*	1
        ///decid*	1
        ///decision*	1
        ///decisive*	1
        ///defeat*	1
        ///deliberat*	1
        ///dependable	1
        ///determin*	1
        ///difficult*	1
        ///do*	1
        ///eager*	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AgencyCommunionDict {
            get {
                return ResourceManager.GetString("AgencyCommunionDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Agitation
        ///2	Dejection
        ///%
        ///scared to death	1
        ///afraid	1
        ///scared	1
        ///horribl*	1
        ///horrifi*	1
        ///terribl*	1
        ///terrifie*	1
        ///terrify*	1
        ///panic*	1
        ///anxi*	1
        ///nervous*	1
        ///worr*	1
        ///concern*	1
        ///tense*	1
        ///tensing	1
        ///tension*	1
        ///troubl*	1
        ///restless*	1
        ///stress*	1
        ///defens*	1
        ///provok*	1
        ///provoc*	1
        ///bitter*	2
        ///unhapp*	2
        ///frustr*	2
        ///irrita*	2
        ///deject*	2
        ///demotiv*	2
        ///heartsick*	2
        ///depriv*	2
        ///stoop*	2
        ///sad	2
        ///sadde*	2
        ///sadly	2
        ///sadness	2
        ///negativ*	2
        ///sorrow*	2
        ///miss	2
        ///missing	2
        ///missed	2
        ///misses	2
        ///depress*	2
        ///miser*	2
        ///trag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Agitation_Dejection_Dictionary {
            get {
                return ResourceManager.GetString("Agitation_Dejection_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Analogy
        ///2	Being
        ///%
        ///alike	1
        ///am	2
        ///are	2
        ///as	1
        ///be	2
        ///being	2
        ///is	2
        ///like	1
        ///resembles	1
        ///same	1
        ///seems	1.
        /// </summary>
        internal static string Analogy_Being_Dictionary {
            get {
                return ResourceManager.GetString("Analogy_Being_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	LongTermfocus
        ///2	ShortTermFocus
        ///3	InternalFocus
        ///4	Externalfocus
        ///%
        ///Future	1
        ///Planned	1
        ///Impending	1
        ///Prospective	1
        ///Later	1
        ///Will	1
        ///May	1
        ///Might	1
        ///Shall	1
        ///Tomorrow	1
        ///Forthcoming	1
        ///Prospect	1
        ///Long-term	1
        ///Long	period*	1
        ///Durable	1
        ///Short-term	2
        ///Now	2
        ///Current*	2
        ///Moment	2
        ///Unstable	2
        ///Temporary	2
        ///Profit	2
        ///Growth	2
        ///Today	2
        ///CEO	3
        ///President	3
        ///Vice-president*	3
        ///Director*	3
        ///Officer	3
        ///Officers	3
        ///Executive*	3
        ///Supervisor*	3
        ///Diversification	3
        ///Diversify	3
        ///Diversified	3
        ///Innovation*	3
        ///Innovations	3
        ///Organization	3
        ///Organizational	3
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Anique_Gregson___Attention_Focus {
            get {
                return ResourceManager.GetString("Anique_Gregson___Attention_Focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	assessments
        ///2	authority
        ///3	causation
        ///4	conditionals
        ///5	contrast
        ///6	difficulty
        ///7	doubt
        ///8	emphasis
        ///9	generalization
        ///10	inconsistency
        ///11	inyourshoes
        ///12	necessity
        ///13	possibility
        ///14	priority
        ///15	rhetoricalquestion
        ///16	structure
        ///17	wants
        ///%
        ///our opinion is that	1
        ///our opinion was that	1
        ///our understanding is that	1
        ///our understanding was that	1
        ///my opinion is that	1
        ///my opinion was that	1
        ///my understanding is that	1
        ///my understanding was that	1
        ///it is our opinion	1
        ///it is our opinion that	1
        ///it is [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ArgLex {
            get {
                return ResourceManager.GetString("ArgLex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Barrier_Total
        ///2	Container
        ///3	Enclosed_Open
        ///4	Protect_Surface
        ///5	Covered_Hidden
        ///6	Special_Struct
        ///7	Shell_Animal
        ///8	Special_Animals
        ///9	Penetration_Tot
        ///10	Entrance_Open
        ///11	Permeable
        ///12	Body_Orifices
        ///13	Autopsy
        ///14	Wounds_Deform
        ///15	Spurt_Excrete
        ///16	Transparency
        ///%
        ///ABCESS*	9	14
        ///ABRAD*	9	14
        ///ABRASION*	9	14
        ///ABYSS*	9	10
        ///ACCES*	9	10
        ///ADORN*	1	4
        ///AEROPLANE*	1	6
        ///AIRCRAFT	1	6
        ///AIRPLANE*	1	6
        ///AISL*	1	4
        ///ALLIGAT*	1	7
        ///ALLIGATOR*	1	8
        ///ANAL*	9	12
        ///ANUS*	9	12
        ///ARCH*	9	10
        ///ARMOR*	1	4
        ///ARMOUR*	1	4
        ///ARSE	9	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Body_Type_Dictionary {
            get {
                return ResourceManager.GetString("Body_Type_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///Competence	1
        ///Excitement	2
        ///Ruggedness	3
        ///Sincerity	4
        ///Sophistication	5
        ///Not_Relevant	6
        ///%
        ///state of the art	2
        ///up to the minute	2
        ///a la mode	5
        ///down to earth	4
        ///hale and hearty	4
        ///hard to pronounce	6
        ///in no doubt	1
        ///out of door	3
        ///out of doors	3
        ///the right way	4
        ///touch and go	3
        ///up and coming	1
        ///up to date	2
        ///able bodied	1
        ///above board	4
        ///al fresco	3
        ///avant garde	2
        ///award winning	1
        ///awe inspiring	2
        ///blue blood	5
        ///blue blooded	5
        ///brand new	2
        ///brush up	5
        ///clean cut	4
        ///clear cut	4
        ///de luxe	5
        ///eye catching	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Brand_Personality {
            get {
                return ResourceManager.GetString("Brand_Personality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Abstraction
        ///%
        ///*ity	1
        ///*ness	1
        ///*nce	1
        ///*ment	1
        ///*any	1
        ///*ncy	1
        ///*ship	1
        ///*dom	1
        ///*ing	1
        ///*ion	1
        ///*ities	1
        ///*nesses	1
        ///*nces	1
        ///*ments	1
        ///*anies	1
        ///*ncies	1
        ///*ships	1
        ///*doms	1
        ///*ings	1
        ///*ions	1.
        /// </summary>
        internal static string Concreteness___Mergenthaler_Suffix {
            get {
                return ResourceManager.GetString("Concreteness___Mergenthaler_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Connectives
        ///%
        ///accordingly	1
        ///additionally	1
        ///after	1
        ///afterward	1
        ///also	1
        ///alternatively	1
        ///although	1
        ///and	1
        ///as	1
        ///as a result	1
        ///as an alternative	1
        ///as if	1
        ///as long as	1
        ///as soon as	1
        ///as though	1
        ///as well	1
        ///because	1
        ///before	1
        ///before and after	1
        ///besides	1
        ///but	1
        ///by comparison	1
        ///by contrast	1
        ///by then	1
        ///consequently	1
        ///conversely	1
        ///earlier	1
        ///either or	1
        ///else	1
        ///except	1
        ///finally	1
        ///for	1
        ///for example	1
        ///for instance	1
        ///further	1
        ///furthermore	1
        ///hence	1
        ///however	1
        ///if	1
        ///if and when	1
        ///i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Connectives {
            get {
                return ResourceManager.GetString("Connectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	HumanRights
        ///2	Employee
        ///3	SocialAndCommunity
        ///4	Environment
        ///%
        ///aboriginal peoples	1
        ///aboriginals	1
        ///abuse	1	2	3	4
        ///abused	3
        ///abuses	3
        ///accept	1	3	4
        ///accepted	1	3	4
        ///accommodating	1	2	3	4
        ///accommodation	1	2	3	4
        ///accompanied	3
        ///accountability	1	2	3	4
        ///accountancy	3
        ///acid rain	4
        ///acid rains	4
        ///activities	1	3	4
        ///acts	1
        ///adopt	1	3	4
        ///adopted	1	3	4
        ///adopted child	2
        ///adopted children	2
        ///adverse	1	4
        ///adversely	1	4
        ///affluence	4
        ///affluences	4
        ///affordable	3
        ///affordable housing	3
        ///african	1
        ///african american	1	2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Corporate_Social_Responsibility {
            get {
                return ResourceManager.GetString("Corporate_Social_Responsibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Positive
        ///2	Negative
        ///3	Anger
        ///4	Anticipation
        ///5	Disgust
        ///6	Fear
        ///7	Joy
        ///8	Sadness
        ///9	Surprise
        ///10	Trust
        ///%
        ///abacus	10
        ///abandon	2	6	8
        ///abandoned	2	3	6	8
        ///abandonment	2	3	6	8	9
        ///abba	1
        ///abbot	10
        ///abduction	2	6	8	9
        ///aberrant	2
        ///aberration	2	5
        ///abhor	2	3	5	6
        ///abhorrent	2	3	5	6
        ///ability	1
        ///abject	2	5
        ///abnormal	2	5
        ///abolish	2	3
        ///abolition	2
        ///abominable	2	5	6
        ///abomination	2	3	5	6
        ///abort	2
        ///abortion	2	5	6	8
        ///abortive	2	8
        ///abovementioned	1
        ///abrasion	2
        ///abrogate	2
        ///abrupt	9
        ///abscess	2	8
        ///absence	2	6	8
        ///absent	2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmoLex092_English {
            get {
                return ResourceManager.GetString("EmoLex092_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Help
        ///2	Office
        ///3	Dance
        ///4	Money
        ///5	Wedding
        ///6	Domestic_Work
        ///7	Sleep
        ///8	Medical_Emergency
        ///9	Cold
        ///10	Hate
        ///11	Cheerfulness
        ///12	Aggression
        ///13	Occupation
        ///14	Envy
        ///15	Anticipation
        ///16	Family
        ///17	Vacation
        ///18	Crime
        ///19	Attractive
        ///20	Masculine
        ///21	Prison
        ///22	Health
        ///23	Pride
        ///24	Dispute
        ///25	Nervousness
        ///26	Government
        ///27	Weakness
        ///28	Horror
        ///29	Swearing_Terms
        ///30	Leisure
        ///31	Suffering
        ///32	Royalty
        ///33	Wealthy
        ///34	Tourism
        ///35	Furniture
        ///36	School
        ///37	Magic
        ///38	Beach
        ///39	Journalism
        ///40	Morning
        ///41	Banking [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmpathDefaultDictionary {
            get {
                return ResourceManager.GetString("EmpathDefaultDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Pornography
        ///2	LIWCsex
        ///3	EssamExt
        ///4	EssamAdj
        ///5	AmSlang
        ///6	Brslang
        ///7	LIWCdrive
        ///8	LIWCporn
        ///%
        ///adolescen*	1	3
        ///adore*	1	7
        ///adulate*	1	3
        ///adulterer*	1	2
        ///adulterous*	1	4
        ///affair*	1	2
        ///affection	1	7
        ///agitation	1	2
        ///aids	1	8
        ///allure*	1	3
        ///aloneness*	1	2
        ///amativeness*	1	7
        ///amatory	1	7
        ///amble*	1	3	7
        ///amor*	1	7
        ///amour*	1	7
        ///anal*	1	4
        ///androgynous*	1	4
        ///animalistic*	1	4
        ///anorgasmia*	1	2
        ///anus*	1	2
        ///aphrodisiac*	1	4
        ///apocalyptic*	1	4
        ///appetence*	1	2
        ///arous*	1	8
        ///arousal	1	2
        ///arse	1	6
        ///asexual*	1	8
        ///ass*	1	2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Encarnacion_S__Arenas___LIWC___Essam_Porn_Dictionary {
            get {
                return ResourceManager.GetString("Encarnacion_S__Arenas___LIWC___Essam_Porn_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	EnglishPrime
        ///%
        ///ain&apos;t	1
        ///aint	1
        ///am	1
        ///are	1
        ///aren&apos;t	1
        ///be	1
        ///been	1
        ///being	1
        ///hain&apos;t	1
        ///here&apos;s	1
        ///heres	1
        ///he&apos;s	1
        ///hes	1
        ///how&apos;s	1
        ///hows	1
        ///I&apos;m	1
        ///Im	1
        ///is	1
        ///isn&apos;t	1
        ///isnt	1
        ///it&apos;s	1
        ///she&apos;s	1
        ///shes	1
        ///that&apos;s	1
        ///thats	1
        ///there&apos;s	1
        ///theres	1
        ///they&apos;re	1
        ///theyre	1
        ///was	1
        ///wasn&apos;t	1
        ///wasnt	1
        ///were	1
        ///we&apos;re	1
        ///weren&apos;t	1
        ///werent	1
        ///whatcha	1
        ///what&apos;s	1
        ///whats	1
        ///where&apos;s	1
        ///wheres	1
        ///who&apos;s	1
        ///whos	1
        ///you&apos;re	1
        ///youre	1.
        /// </summary>
        internal static string English_Prime {
            get {
                return ResourceManager.GetString("English_Prime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Negative
        ///2	Positive
        ///3	Uncertainty
        ///4	Litigious
        ///5	StrongModal
        ///6	WeakModal
        ///7	Constraining
        ///%
        ///abandon	1
        ///abandoned	1
        ///abandoning	1
        ///abandonment	1
        ///abandonments	1
        ///abandons	1
        ///abdicated	1
        ///abdicates	1
        ///abdicating	1
        ///abdication	1
        ///abdications	1
        ///aberrant	1
        ///aberration	1
        ///aberrational	1
        ///aberrations	1
        ///abetting	1
        ///abeyance	3
        ///abeyances	3
        ///abide	7
        ///abiding	7
        ///able	2
        ///abnormal	1
        ///abnormalities	1
        ///abnormality	1
        ///abnormally	1
        ///abolish	1
        ///abolished	1
        ///abolishes	1
        ///abolishing	1
        ///abovementioned	4
        ///abrogate	1	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FinancialSentimentDictionary2018 {
            get {
                return ResourceManager.GetString("FinancialSentimentDictionary2018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	EconomicUtilitarian
        ///2	LifeSupport
        ///3	Aesthetic
        ///4	MoralSpiritual
        ///%
        ///ABSORB AIR POLLUTANTS	2
        ///ABSORPTION OF POLLUTANTS	2
        ///ACID DRAINAGE	2
        ///ACID PRECIPITATION	2
        ///ACID RAIN	2
        ///ADORN	3
        ///ADORNED	3
        ///AESTHETIC	3
        ///AESTHETICALLY	3
        ///AFFECTIVE	3
        ///AIR AND WATER	2
        ///AIR PURIFIER	2
        ///AIR PURIFY	2
        ///AIR PURIFYING	2
        ///AIR QUALITY	2
        ///AMELIORATING	2
        ///ANCIENT FOREST	4
        ///ANCIENT TREE	4
        ///ANTHROPOCENTRIC	4
        ///AQUATIC LIFE	2
        ///AQUATIC ZONE	2
        ///ARTIST	3
        ///ARTISTIC	3
        ///ARTIST&apos;S	3
        ///ASSIMILATIVE CAPACITY	2
        ///AWE	3
        ///AWE-INSPIRING	3
        ///AWESOM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Forest_Value_Dictionary {
            get {
                return ResourceManager.GetString("Forest_Value_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	GlobalCitizen
        ///%
        ///accountable	1
        ///advocate	1
        ///agree	1
        ///agreement*	1
        ///appreciat*	1
        ///associat*	1
        ///aware*	1
        ///bound*	1
        ///care	1
        ///cares	1
        ///caring	1
        ///chargeable	1
        ///citizen	1
        ///citizens	1
        ///civilization	1
        ///climate	1
        ///colony	1
        ///commitment*	1
        ///common	1
        ///commun*	1
        ///connect*	1
        ///conscious*	1
        ///consider	1
        ///considerate	1
        ///cooperate	1
        ///cosmopolitan	1
        ///countr*	1
        ///courteous	1
        ///culpable	1
        ///cultur*	1
        ///decency	1
        ///decent	1
        ///different	1
        ///dignity	1
        ///divers*	1
        ///duti*	1
        ///duty	1
        ///earth*	1
        ///ecology	1
        ///educat*	1
        ///embrace	1
        ///embracing	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Global_Citizen_Dictionary {
            get {
                return ResourceManager.GetString("Global_Citizen_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Ability
        ///2	Achievement
        ///3	Agentic
        ///4	NegEval
        ///5	PosEval
        ///6	Research
        ///7	StandoutAdj
        ///%
        ///abilit*	1	2
        ///able	1
        ///able*	2
        ///accept*	5
        ///accomplish*	2	3	5
        ///ace	2
        ///achiev*	2	3
        ///acquir*	2
        ///acquisition*	2
        ///active*	3
        ///adept*	1
        ///adequa*	2
        ///adroit*	1
        ///advanc*	2	5
        ///advantag*	2
        ///agentic	3
        ///agress*	3
        ///ahead	2
        ///amazing	7
        ///ambiti*	2	3
        ///ambitio*	5
        ///analy*	1	3
        ///appropriat*	5
        ///approv*	2
        ///aptitude	1
        ///art	5
        ///assert*	3
        ///assiduous*	3
        ///assurance	3
        ///attain*	2
        ///attempt*	2
        ///authorit*	2
        ///award*	2
        ///beat*	2
        ///believabl*	5
        ///best	2	5
        ///bet [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GrantEvalDic {
            get {
                return ResourceManager.GetString("GrantEvalDic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Deadline
        ///2	Desperation
        ///3	Fixation
        ///4	Frustration
        ///5	God
        ///6	Grievance
        ///7	Hate
        ///8	Help
        ///9	Honour
        ///10	Impostor
        ///11	Jealousy
        ///12	Loneliness
        ///13	Murder
        ///14	Paranoia
        ///15	Planning
        ///16	Relationship
        ///17	Soldier
        ///18	Suicide
        ///19	Surveillance
        ///20	Threat
        ///21	Violence
        ///22	Weaponry
        ///%
        ///155mm	22
        ///911	8
        ///abandon	12
        ///abduct	20	21
        ///abhor	7
        ///abid by	5	9
        ///abus	13	21
        ///accid	8
        ///accompani	8
        ///accomplic	13
        ///accomplish	1
        ///accuraci	15
        ///accus	14
        ///achiev	9
        ///acrid	7
        ///act as	10
        ///act of terror	7	20	21
        ///act upon	15
        ///action	1	15
        ///acti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GrievanceDictionary {
            get {
                return ResourceManager.GetString("GrievanceDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Positiv
        ///2	Negativ
        ///3	Pstv
        ///4	Affil
        ///5	Ngtv
        ///6	Hostile
        ///7	Strong
        ///8	Power
        ///9	Weak
        ///10	Submit
        ///11	Active
        ///12	Passive
        ///13	Pleasur
        ///14	Pain
        ///15	Feel
        ///16	Arousal
        ///17	EMOT
        ///18	Virtue
        ///19	Vice
        ///20	Ovrst
        ///21	Undrst
        ///22	Academ
        ///23	Doctrin
        ///24	Econ2
        ///25	Exch
        ///26	ECON
        ///27	Exprsv
        ///28	Legal
        ///29	Milit
        ///30	Polit2
        ///31	POLIT
        ///32	Relig
        ///33	Role
        ///34	COLL
        ///35	Work
        ///36	Ritual
        ///37	SocRel
        ///38	Race
        ///39	Kin2
        ///40	MALE
        ///41	Female
        ///42	Nonadlt
        ///43	HU
        ///44	ANI
        ///45	PLACE
        ///46	Social
        ///47	Region
        ///48	Route
        ///49	Aquatic
        ///50	Land
        ///51	Sky
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Harvard_General_Inquirer_IV___FULL {
            get {
                return ResourceManager.GetString("Harvard_General_Inquirer_IV___FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Hedges
        ///%
        ///think	1
        ///thought	1
        ///thinking	1
        ///almost	1
        ///apparent	1
        ///apparently	1
        ///appear	1
        ///appeared	1
        ///appears	1
        ///approximately	1
        ///around	1
        ///assume	1
        ///assumed	1
        ///certain amount	1
        ///certain extent	1
        ///certain level	1
        ///claim	1
        ///claimed	1
        ///doubt	1
        ///doubtful	1
        ///essentially	1
        ///estimate	1
        ///estimated	1
        ///feel	1
        ///felt	1
        ///frequently	1
        ///from our perspective	1
        ///generally	1
        ///guess	1
        ///in general	1
        ///in most cases	1
        ///in most instances	1
        ///in our view	1
        ///indicate	1
        ///indicated	1
        ///largely	1
        ///likely	1
        ///mainly	1
        ///may	1
        ///maybe	1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Hedges {
            get {
                return ResourceManager.GetString("Hedges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Anticipation
        ///2	Positive
        ///3	Negative
        ///4	Trust
        ///5	Joy
        ///6	Fear
        ///7	Surprise
        ///8	Anger
        ///9	Disgust
        ///10	Sadness
        ///%
        ///abundance	1	2	3	4	5	9
        ///accelerat*	1
        ///accolade*	1	2	4	5	7
        ///accompaniment*	1	2	4	5
        ///achievement*	1	2	4	5
        ///acquiring	1	2
        ///addresses	1	2
        ///ador*	1	2	5
        ///adrift	1	3	6	10
        ///advance*	1	2	5	6	7
        ///advent*	1	2	5
        ///adventure*	1	2
        ///advocacy	1	2	4	5	8
        ///airport*	1
        ///alertness	1	2	6	7
        ///alerts	1	6	7
        ///alive	1	2	5
        ///allur*	1	2	5	7
        ///aloha	1	2	5
        ///ambition*	1	2	5
        ///amour*	1	2	5
        ///analyst*	1	2	4
        ///angel*	1	2	4	5	7
        ///angling*	1	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Hogenraad_Anticipation_Dictionary {
            get {
                return ResourceManager.GetString("Hogenraad_Anticipation_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Total
        ///2	Renewal
        ///3	Alterations
        ///4	Vision
        ///5	Fabulations
        ///6	Infinity_Eternity
        ///7	Enchantment_Emotions
        ///8	Cogs_Precogs
        ///9	Spiritual_Imagery
        ///%
        ///abracadabra*	1	3
        ///absolute*	1	6
        ///accommod*	1	3
        ///accomplished	1	6
        ///adaptation*	1	3
        ///adjustment*	1	3
        ///adored*	1	9
        ///adumbrate*	1	8
        ///advance*	1	2
        ///ahead	1	8
        ///alchem*	1	3
        ///alien*	1	8
        ///allegor*	1	5
        ///allur*	1	7
        ///altera*	1	3
        ///ameliorat*	1	3
        ///amend*	1	3
        ///amulet*	1	7
        ///angel*	1	9
        ///annunciation*	1	9
        ///antichrist*	1	9
        ///anticip*	1	8
        ///apocalyp*	1	9
        ///apostle*	1	9
        ///apparition*	1	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Hogenraad_Metamorphosis_Dictionary {
            get {
                return ResourceManager.GetString("Hogenraad_Metamorphosis_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Clutter
        ///2	House_Unfinished
        ///3	Restful
        ///4	Nature
        ///5	Stressful_Home
        ///6	Restorative_Home
        ///%
        ///mess	1	5
        ///messy	1	5
        ///clutter	1	5
        ///cluttered	1	5
        ///junk	1	5
        ///disarray	1	5
        ///unorganized	1	5
        ///disorganized	1	5
        ///disorder	1	5
        ///disorderly	1	5
        ///disordered	1	5
        ///overflow	1	5
        ///overflowing	1	5
        ///disaster	1	5
        ///haphazard	1	5
        ///trash	1	5
        ///trashy	1	5
        ///trashed	1	5
        ///sloppy	1	5
        ///chaos	1	5
        ///chaotic	1	5
        ///unfinished	2	5
        ///half-finished	2	5
        ///repair	2	5
        ///fix	2	5
        ///redo	2	5
        ///remodel	2	5
        ///expansion	2	5
        ///addiiton	2	5
        ///project	2	5
        ///build	2	5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Home_Perceptions_Dictionary {
            get {
                return ResourceManager.GetString("Home_Perceptions_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///500	Overall_Honor_Dictionary
        ///504	Honor_Gain
        ///540	Honor_Gain_Virtuous_Behavior
        ///507	Virtuous_Behavior_Moral_Integrity
        ///509	Virtuous_Behavior_Faith
        ///532	Virtuous_Behavior_Manners
        ///505	Honor_Gain_AchieveStatus
        ///511	AchieveStatus_Achieve
        ///506	AchieveStatus_Status
        ///513	Honor_Protection
        ///515	Honor_Protection_Public_Image
        ///527	Honor_Protection_Strength/Bravery
        ///516	Honor_Protection_Prevention
        ///514	Honor_Protection_Sex
        ///501	Honor_Loss
        ///502	Honor_Loss_Wrongdoing
        ///503	Honor_Loss_Harm
        ///535	Honor_Loss_Aggression
        ///5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HonorDictionary {
            get {
                return ResourceManager.GetString("HonorDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///01	General
        ///02	Awe
        ///03	Gratitude
        ///04	Elevation
        ///05	Admiration
        ///06	Hope
        ///%
        ///
        ///acclaim*	05
        ///accomplish*	01
        ///achiev*	05	06
        ///acknowledg*	03
        ///admir*	02	03	05
        ///ador*	05
        ///adulat*	05
        ///advanc*	04
        ///aesthetic	02
        ///affection	03	05
        ///almighty	03
        ///amazing	02	05
        ///amazed	02	05
        ///ambition	05	06
        ///amplify	04
        ///anticipat*	06
        ///applau*	05
        ///appreciat*	03	05
        ///approbation	05
        ///approv*	05
        ///artist*	05
        ///ascen*	04
        ///aspir*	06
        ///assum*	06
        ///assur*	06
        ///astonish*	02
        ///at ease	06
        ///auspicious	06
        ///await	06
        ///awake*	02
        ///awe*	02	05
        ///beaut*	02	05
        ///bel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ji_Raney_Self_Transcendent_Emotion_Dictionary {
            get {
                return ResourceManager.GetString("Ji_Raney_Self_Transcendent_Emotion_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Culture
        ///2	Culture_High
        ///3	Culture_Popular
        ///4	Sport
        ///5	Economy
        ///6	State_More
        ///7	State_Equal
        ///8	State_Less
        ///9	Environment
        ///10	Con_Environment
        ///11	Pro_Environment
        ///12	Groups
        ///13	Ethnic
        ///14	Women
        ///15	Rural
        ///16	Urban
        ///17	Institutions
        ///18	Inst_Conservative
        ///19	Inst_Neutral
        ///20	Inst_Radical
        ///21	Law_And_Order
        ///22	Law_Conservative
        ///23	Law_Liberal
        ///24	Values
        ///25	Values_Conservative
        ///26	Values_Liberal
        ///%
        ///ABOLITION	17	20
        ///ACCOMMODATION	5	6
        ///ACCOUNTABLE	17	20
        ///ACCOUNTANT	5	7
        ///ACCOUNTING	5	7
        ///ACCOUNTS	5	7
        ///ADMINIS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Laver_Garry_Dictionary_of_Policy_Position {
            get {
                return ResourceManager.GetString("Laver_Garry_Dictionary_of_Policy_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	DAV
        ///2	IAV
        ///3	SV
        ///%
        ///abandon	2
        ///abandoned	2
        ///abandoning	2
        ///abandons	2
        ///abhor	3
        ///abhorred	3
        ///abhorring	3
        ///abhors	3
        ///absorb	1
        ///absorbed	1
        ///absorbing	1
        ///absorbs	1
        ///abuse	2
        ///abused	2
        ///abuses	2
        ///abusing	2
        ///accede	2
        ///acceded	2
        ///accedes	2
        ///acceding	2
        ///accelerate	1
        ///accelerated	1
        ///accelerates	1
        ///accelerating	1
        ///accentuate	2
        ///accentuated	2
        ///accentuates	2
        ///accentuating	2
        ///accept	2
        ///accepted	2
        ///accepting	2
        ///accepts	2
        ///accommodate	2
        ///accommodated	2
        ///accommodates	2
        ///accommodating	2
        ///accompanied	1
        ///accompanies	1
        ///ac [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LCM {
            get {
                return ResourceManager.GetString("LCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Aboriginal
        ///2	Agriculture
        ///3	Civil_Rights
        ///4	Constitutional_Natl_Unity
        ///5	Crime
        ///6	Culture
        ///7	Defence
        ///8	Education
        ///9	Energy
        ///10	Environment
        ///11	Finance
        ///12	Fisheries
        ///13	Foreign_Trade
        ///14	Forestry
        ///15	Government_Ops
        ///16	Healthcare
        ///17	Housing
        ///18	Immigration
        ///19	Intergovernmental
        ///20	Intl_Affairs
        ///21	Labour
        ///22	Land-Water-Management
        ///23	Macroeconomics
        ///24	Prov_Local
        ///25	Religion
        ///26	Social_Welfare
        ///27	Sstc
        ///28	Transportation
        ///%
        ///CANADIAN OFFICE AND PROFESSIONAL EMPLOYEES UNION*	21
        ///UNION OF PUBLIC AND [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Lexicoder_Topic_Dictionary {
            get {
                return ResourceManager.GetString("Lexicoder_Topic_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Action
        ///2	Inaction
        ///%
        ///abilit*	1
        ///able*	1
        ///abst*	2
        ///accomplish*	1
        ///ace	1
        ///achiev*	1
        ///acquir*	1
        ///acquisition*	1
        ///act	1
        ///acted	1
        ///acting	1
        ///action*	1
        ///activat*	1
        ///acts	1
        ///adjourn*	2
        ///advanc*	1
        ///aerobic*	1
        ///affect*	1
        ///ahead	1
        ///allay*	2
        ///alleviat*	2
        ///ambiti*	1
        ///apath*	2
        ///appeas*	2
        ///appreciat*	1
        ///approach*	1
        ///approv*	1
        ///armistice*	2
        ///arrival*	1
        ///arrive	1
        ///arrived	1
        ///arrives	1
        ///arriving	1
        ///ask	1
        ///asked	1
        ///asking	1
        ///asks	1
        ///assuag*	2
        ///assur*	1
        ///athletic*	1
        ///attain*	1
        ///attempt*	1
        ///attend	1
        ///attended	1
        ///attendi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LUSI___Action_Inaction_Dictionary {
            get {
                return ResourceManager.GetString("LUSI___Action_Inaction_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Bored
        ///2	Tired
        ///3	Frustrated
        ///4	Total_disengaged
        ///5	Swear
        ///%
        ///banal	1	4
        ///blah*	1	4
        ///blahs	1	4
        ///bluh*	1	4
        ///bore	1	4
        ///bored	1	4
        ///boredom	1	4
        ///bores	1	4
        ///boring	1	4
        ///dull	1	4
        ///dullest	1	4
        ///dully	1	4
        ///ennui	1	4
        ///fidget*	1	4
        ///idle	1	4
        ///idly	1	4
        ///listless*	1	4
        ///meh	1	4
        ///mope	1	4
        ///moper*	1	4
        ///mopes	1	4
        ///moping	1	4
        ///restless*	1	4
        ///sulk*	1	4
        ///tiresome*	1	4
        ///vacantly	1	4
        ///world-wear	1	4
        ///am pooped	2	4
        ///are pooped	2	4
        ///I&apos;m pooped	2	4
        ///look pooped	2	4
        ///bedtime	2	4
        ///burned out	2	4
        ///burnout	2	4
        ///burnt out	2	4
        ///drows [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LUSI___Disengagement_Dictionary___Modified {
            get {
                return ResourceManager.GetString("LUSI___Disengagement_Dictionary___Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	leetspeak
        ///2	txtspeak
        ///3	internetism
        ///4	sounds
        ///5	gaming
        ///6	slang
        ///7	technology
        ///8	fandom
        ///9	swear
        ///10	contextual
        ///11	political
        ///12	url
        ///%
        ///1337	1
        ///31337	1
        ///http*	12
        ///www*	12
        ///@	3
        ///0wn*	1
        ///2ds	5
        ///2gether	2
        ///3ds	5
        ///4chan	7
        ///4ev*	2
        ///4tlog	2	9
        ///4tw	1
        ///8chan	7
        ///abt	2
        ///accriat*	3
        ///adblock*	7
        ///admin	7
        ///adorbs	3
        ///adorbz	3
        ///adsl	7
        ///adulting	3
        ///adwall*	7
        ///af	2	9
        ///afai*	2
        ///afk	2	5
        ///agro	5	6
        ///ahh*	4
        ///ai	7
        ///aight	6
        ///aka	2
        ///aliasing	7
        ///ama	7
        ///amd	7
        ///amg	3
        ///amiright*	3
        ///amirite*	3
        ///anime*	8
        ///animu*	8	3
        ///any1	2
        ///ao3	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LUSI___Netspeak_Dictionary {
            get {
                return ResourceManager.GetString("LUSI___Netspeak_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	RiskySex
        ///%
        ///amorous	1
        ///anal	1
        ///analingus	1
        ///anally	1
        ///anus	1
        ///arous*	1
        ///arse*	1
        ///ass	1
        ///asses	1
        ///assfuck*	1
        ///ass-fuck*	1
        ///autoerotic	1
        ///bajingo	1
        ///balled	1
        ///ballsack*	1
        ///bareback*	1
        ///beej	1
        ///beejay	1
        ///bbbj	1
        ///bbbjs	1
        ///bj	1
        ///bjs	1
        ///blowjob*	1
        ///blowy*	1
        ///boner*	1
        ///boning	1
        ///boob*	1
        ///booty	1
        ///bosom*	1
        ///breast*	1
        ///bukake	1
        ///bukakke	1
        ///bukkake	1
        ///bumfuck*	1
        ///bum-fuck*	1
        ///butt	1
        ///buttcrack	1
        ///buttfuck*	1
        ///butt-fuck*	1
        ///butthole	1
        ///butts	1
        ///butt&apos;s	1
        ///buttsex	1
        ///chode*	1
        ///clit	1
        ///clitoris	1
        ///cock	1
        ///cockblock [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LUSI___Risky_Sex_Dictionary {
            get {
                return ResourceManager.GetString("LUSI___Risky_Sex_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	HighControversial
        ///2	MediumControversial
        ///3	LowControversial
        ///%
        ///60s	3
        ///70s	3
        ///abuse	1
        ///account	2
        ///addition	3
        ///address	3
        ///administration	1
        ///advantage	2
        ///afghanistan	1
        ///afternoon	3
        ///agreed	3
        ///aid	1
        ///america	1
        ///american	1
        ///amount	2
        ///amp	3
        ///angeles	3
        ///answer	3
        ///april	3
        ///army	1
        ///attack	1
        ///attacks	1
        ///attention	3
        ///attorney	2
        ///authorities	1
        ///authority	1
        ///avenue	3
        ///average	3
        ///ball	3
        ///ban	1
        ///banks	1
        ///base	3
        ///bay	3
        ///beach	3
        ///beginning	3
        ///benefits	1
        ///bill	1
        ///bills	1
        ///bit	3
        ///block	3
        ///blue	3
        ///border	1
        ///bowl	3
        ///box	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mejova_et_al_2014_controversial_words {
            get {
                return ResourceManager.GetString("Mejova_et_al_2014_controversial_words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Care_Virtue
        ///2	Care_Vice
        ///3	Fairness_Virtue
        ///4	Fairness_Vice
        ///5	Loyalty_Virtue
        ///6	Loyalty_Vice
        ///7	Authority_Virtue
        ///8	Authority_Vice
        ///9	Sanctity_Virtue
        ///10	Sanctity_Vice
        ///%
        ///compassion	1
        ///empathy	1
        ///kindness	1
        ///caring	1
        ///generosity	1
        ///benevolence	1
        ///altruism	1
        ///compassionate	1
        ///nurture	1
        ///gentleness	1
        ///nurturance	1
        ///sympathy	1
        ///nurturing	1
        ///motherly	1
        ///love	1
        ///beneficence	1
        ///empathize	1
        ///helpfulness	1
        ///loving	1
        ///pity	1
        ///mercy	1
        ///nurturer	1
        ///compassionately	1
        ///nurturers	1
        ///caringly	1
        ///empathising	1
        ///mer [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mfd2_0 {
            get {
                return ResourceManager.GetString("mfd2_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Experience
        ///2	Agency
        ///3	PatientRelatedEmotions
        ///4	AgentRelatedEmotions
        ///5	MindOverall
        ///%
        ///Feel*	5	1
        ///Perceive*	5	1
        ///Perception	5	1
        ///Mood	5	1
        ///Pain	5	1
        ///Ache*	5	1
        ///Agony	5	1
        ///Discomfort	5	1
        ///Injur*	5	1
        ///Wound*	5	1
        ///Miser*	5	1
        ///Distress*	5	1
        ///Anguish*	5	1
        ///Anxiety	5	1
        ///Anxious	5	1
        ///Grief	5	1
        ///Sad*	5	1
        ///Devastated	5	1
        ///Suffer*	5	1
        ///Hurt*	5	1
        ///Emotion*	5	1
        ///Anger	5	1	4
        ///Angry	5	1	4
        ///Surprise*	5	1
        ///Disgust*	5	1	4
        ///Pleasure	5	1
        ///Amuse*	5	1
        ///Enjoy*	5	1
        ///Gratif*	5	1
        ///Passon*	5	1
        ///Purpose	5	2
        ///Plan*	5	2
        ///Prepar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mind_Perception_Dictionary {
            get {
                return ResourceManager.GetString("Mind_Perception_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Mindfulness
        ///%
        ///Accept*	1
        ///Allow*	1
        ///Attention	1
        ///Automatic	1
        ///Autopilot	1
        ///Aware*	1
        ///Balanc*	1
        ///Being	1
        ///Body	1
        ///Breath*	1
        ///Calm*	1
        ///Center*	1
        ///Choice*	1
        ///Commit*	1
        ///Compassion*	1
        ///curiosity	1
        ///Discomfort*	1
        ///Ease	1
        ///Emotion*	1
        ///Energ*	1
        ///Experienc*	1
        ///Expand*	1
        ///Feel*	1
        ///Fight*	1
        ///Fix*	1
        ///Free*	1
        ///friend*	1
        ///Gentle*	1
        ///Grateful	1
        ///Gratitude	1
        ///Judg*	1
        ///Kind*	1
        ///Let*	1
        ///Meditat*	1
        ///Mindful*	1
        ///Moment*	1
        ///Nonjudg*	1
        ///Notic*	1
        ///Now	1
        ///Ok	1
        ///Observ*	1
        ///Open*	1
        ///Paus*	1
        ///Peace	1
        ///Practice	1
        ///Present	1
        ///Pu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mindfulness_Dictionary {
            get {
                return ResourceManager.GetString("Mindfulness_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	HarmVirtue
        ///2	HarmVice
        ///3	FairnessVirtue
        ///4	FairnessVice
        ///5	IngroupVirtue
        ///6	IngroupVice
        ///7	AuthorityVirtue
        ///8	AuthorityVice
        ///9	PurityVirtue
        ///10	PurityVice
        ///11	MoralityGeneral
        ///%
        ///safe*	1
        ///peace*	1
        ///compassion*	1
        ///empath*	1
        ///sympath*	1
        ///care	1
        ///caring	1
        ///protect*	1
        ///shield	1
        ///shelter	1
        ///amity	1
        ///secur*	1
        ///benefit*	1
        ///defen*	1
        ///guard*	1
        ///preserve	1	7	9
        ///harm*	2
        ///suffer*	2
        ///war	2
        ///wars	2
        ///warl*	2
        ///warring	2
        ///fight*	2
        ///violen*	2
        ///hurt*	2
        ///kill	2
        ///kills	2
        ///killer*	2
        ///killed	2
        ///killing	2
        ///endanger*	2
        ///cruel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Moral_Foundations_Dictionary__Fixed_Formatting_ {
            get {
                return ResourceManager.GetString("Moral_Foundations_Dictionary__Fixed_Formatting_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Deontology
        ///2	Consequentialism
        ///3	Moral_Emotions_General
        ///4	Contempt
        ///5	Anger
        ///6	Disgust
        ///7	Shame
        ///8	Embarrassment
        ///9	Guilt
        ///10	Compassion
        ///11	Gratitude
        ///12	Elevation
        ///%
        ///abominabl*	3	6
        ///acceptable	1
        ///accountab*	1
        ///adher*	1
        ///admir*	3	12
        ///advantage*	2
        ///affronted	3	5
        ///allowed	1
        ///anger*	3	5
        ///angry	3	5
        ///annoy*	3	5
        ///antagoniz*	3	5
        ///appall*	3	6
        ///appreciative	3	11
        ///ashamed	3	7
        ///atroci*	3
        ///authoriz*	1
        ///aversi*	3	6
        ///awe*	3	12
        ///awkward	3	8
        ///banned	1
        ///benefi*	2
        ///bitter	3	5
        ///blame*	3	9
        ///calling	1
        ///code	1
        ///codes	1        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Moral_Justification_Dictionary {
            get {
                return ResourceManager.GetString("Moral_Justification_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Subjective_Total
        ///2	Subjective_Strong
        ///3	Subjective_Weak
        ///4	Negative
        ///5	Neutral
        ///6	Positive
        ///%
        ///abandon	1	3	4
        ///abandoned	1	3	4
        ///abandonment	1	3	4
        ///abase	1	2	4
        ///abasement	1	2	4
        ///abash	1	2	4
        ///abate	1	3	4
        ///abdicate	1	3	4
        ///aberration	1	2	4
        ///abhor	1	2	4
        ///abhorred	1	2	4
        ///abhorrence	1	2	4
        ///abhorrent	1	2	4
        ///abhorrently	1	2	4
        ///abhors	1	2	4
        ///abidance	1	2	6
        ///abide	1	2	6
        ///abilities	1	3	6
        ///ability	1	3	6
        ///abject	1	2	4
        ///abjectly	1	2	4
        ///abjure	1	3	4
        ///able	1	3	6
        ///abnormal	1	3	4
        ///abolish	1	3	4
        ///abominable	1	2	4
        ///abomina [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MPQA_Subjectivity_Lexicon {
            get {
                return ResourceManager.GetString("MPQA_Subjectivity_Lexicon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Black
        ///2	Blue
        ///3	Brown
        ///4	Green
        ///5	Grey
        ///6	None
        ///7	Orange
        ///8	Pink
        ///9	Purple
        ///10	Red
        ///11	White
        ///12	Yellow
        ///%
        ///aback	3
        ///abacus	6
        ///abandon	7
        ///abandoned	1	5
        ///abandonment	1	2	5	6
        ///abate	5	6
        ///abatement	3
        ///abba	6
        ///abbot	9
        ///abbreviate	5	9
        ///abbreviation	1	4
        ///abdomen	6
        ///abdominal	8
        ///abduction	1	10	11
        ///aberrant	6	7	8
        ///aberration	1	4	7	10
        ///abeyance	1	2	5
        ///abhor	1	3	10
        ///abhorrent	1	3
        ///abide	4
        ///ability	4	7	8	10
        ///abject	1	3
        ///ablation	5	10	11
        ///ablaze	10
        ///abnormal	1
        ///aboard	2
        ///abode	3
        ///abolish	6
        ///abolition	1
        ///abominabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NRC_Colour {
            get {
                return ResourceManager.GetString("NRC_Colour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Positive
        ///2	Negative
        ///%
        ///2-faced	2
        ///2-faces	2
        ///abnormal	2
        ///abolish	2
        ///abominable	2
        ///abominably	2
        ///abominate	2
        ///abomination	2
        ///abort	2
        ///aborted	2
        ///aborts	2
        ///abound	1
        ///abounds	1
        ///abrade	2
        ///abrasive	2
        ///abrupt	2
        ///abruptly	2
        ///abscond	2
        ///absence	2
        ///absentee	2
        ///absent-minded	2
        ///absurd	2
        ///absurdity	2
        ///absurdly	2
        ///absurdness	2
        ///abundance	1
        ///abundant	1
        ///abuse	2
        ///abused	2
        ///abuses	2
        ///abusive	2
        ///abysmal	2
        ///abysmally	2
        ///abyss	2
        ///accessable	1
        ///accessible	1
        ///accidental	2
        ///acclaim	1
        ///acclaimed	1
        ///acclamation	1
        ///accolad [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Opinion_Lexicon {
            get {
                return ResourceManager.GetString("Opinion_Lexicon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Total
        ///2	Sensory
        ///3	Affect
        ///4	SensAff
        ///5	Medical
        ///%
        ///abrasion*	1	2	4
        ///abstrak	1	5
        ///acetaminophen	1	5
        ///ache*	1	2	4
        ///aching*	1	2	4
        ///advil	1	5
        ///affliction*	1	3	4
        ///agoniz*	1	3	4
        ///agony	1	3	4
        ///aleve	1	5
        ///algesia	1	5
        ///allodynia	1	5
        ///arthr*	1	5
        ///asprin	1	5
        ///atrophy	1	2	4
        ///beat*	1	3	4
        ///boo-boo*	1	3	4
        ///bone	1	5
        ///bones	1	5
        ///broke*	1	5
        ///bruis*	1	2	4
        ///brutal*	1	3	4
        ///bulding disc*	1	5
        ///carpal	1	5
        ///contusion*	1	5
        ///codeine	1	5
        ///corticosteriod*	1	5
        ///cramp*	1	2	4
        ///crps	1	5
        ///damag*	1	5
        ///decay*	1	5
        ///demerol	1	5
        ///disabili [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Pain_Dictionary {
            get {
                return ResourceManager.GetString("Pain_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	General_Negative_Affect
        ///2	General_Positive_Affect
        ///3	Basic_Negative_Emotions
        ///4	Fear
        ///5	Hostility
        ///6	Guilt
        ///7	Sadness
        ///8	Basic_Positive_Emotions
        ///9	Joviality
        ///10	Self-Assurance
        ///11	Attentiveness
        ///12	Other_Affective_States
        ///13	Shyness
        ///14	Fatigue
        ///15	Serenity
        ///16	Surprise
        ///%
        ///active	2
        ///afraid	1	4	3
        ///alert	2	11	8
        ///alone	7	3
        ///amazed	16	12
        ///angry	5	3
        ///angry at self	6	3
        ///ashamed	1	6	3
        ///astonished	16	12
        ///at ease	15	12
        ///attentive	2	11	8
        ///bashful	13	12
        ///blameworthy	6	3
        ///blue	7	3
        ///bold	10	8
        ///calm	15	12
        ///cheerf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PANASX {
            get {
                return ResourceManager.GetString("PANASX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Invectives
        ///%
        ///abnormal	1
        ///abusive	1
        ///afraid	1
        ///angry	1
        ///annoyed	1
        ///anti-semitic	1
        ///argumentative	1
        ///arrogan	1
        ///arrogant	1
        ///ass	1
        ///awful	1
        ///bad	1
        ///bitch	1
        ///bitter	1
        ///blind	1
        ///cheat	1
        ///cock	1
        ///conceited	1
        ///corrupt	1
        ///crabby	1
        ///critical	1
        ///cruel	1
        ///danger	1
        ///dangerous	1
        ///demanding	1
        ///depressed	1
        ///dick	1
        ///die	1
        ///disappointed	1
        ///disgusting	1
        ///dishonest	1
        ///Disrespectful	1
        ///dumb	1
        ///evil	1
        ///fired	1
        ///frightening	1
        ///frustrated	1
        ///fuck	1
        ///good-for-nothing	1
        ///greedy	1
        ///grumpy	1
        ///gun	1
        ///hate	1
        ///homophobic	1
        ///Horri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Panter_2017___Invectives {
            get {
                return ResourceManager.GetString("Panter 2017 - Invectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Conservation
        ///2	SelfTranscendence
        ///3	OpennessToChange
        ///4	SelfEnhancement
        ///5	Security
        ///6	Conformity
        ///7	Tradition
        ///8	Benevolence
        ///9	Universalism
        ///10	SelfDirection
        ///11	Stimulation
        ///12	Hedonism
        ///13	Achievement
        ///14	Power
        ///%
        ///abide	1	6
        ///ability	3	10
        ///accept	2	9
        ///acceptance	2	9
        ///accomplish	4	13
        ///accomplished	4	13
        ///accord	1	6
        ///accordance	1	6
        ///accustomed	1	7
        ///achieve	4	13
        ///achievement	4	13
        ///achieving	4	13
        ///acknowledge	2	9
        ///acknowledgement	2	9
        ///acknowledging	2	9
        ///acquaintance	2	8
        ///acquire	4	14
        ///act	3	10
        ///acted	3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Personal_Values_Dictionary {
            get {
                return ResourceManager.GetString("Personal_Values_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///800	PrivTtl
        ///801	Intimacy
        ///811	Law
        ///821	NegativePrivacy
        ///831	NormsRequisites
        ///841	OpenVisible
        ///851	OutcomeState
        ///861	PrivateSecret
        ///871	Restriction
        ///%
        ///access	800	841
        ///accessed	800	821	841
        ///accessible	800	841
        ///afraid	800	821
        ///alone	800	851
        ///amendment	800	811
        ///anonymity	800	851
        ///anonymous	800	851
        ///anonymously	800	851
        ///avoided	800	871
        ///avoiding	800	871
        ///behaving	800	861
        ///blacklisted	800	821
        ///blacklisting	800	821
        ///blackmail*	800	821
        ///block	800	871
        ///blocked	800	871
        ///blocking	800	871
        ///boundaries	800	871
        ///boun [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Privacy_Dictionary {
            get {
                return ResourceManager.GetString("Privacy_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	AylanKurdi
        ///2	Prorefugee
        ///3	Threat
        ///4	CollectiveAction
        ///%
        ///Aylan Kurdi	1
        ///Aylankurdi	1
        ///#Aylankurdi	1
        ///Aylan	1
        ///Kurdi	1
        ///#Alankurdi	1
        ///#Syrianchild	1
        ///Syrianchild	1
        ///Syrian child	1
        ///Syrianboy	1
        ///#Syrianboy	1
        ///Prorefugee	2
        ///#refugeeswelcome	2
        ///refugees welcome	2
        ///refugee welcome	2
        ///welcome	2
        ///support for refugee*	2
        ///supportforrefugee*	2
        ///#supportforrefugee*	2
        ///support refugee*	2
        ///support migrants	2
        ///support migrant	2
        ///supportmigrants	2
        ///supportmigrant	2
        ///#supportmigrant*	2
        ///pray	2
        ///#pray*	2
        ///shameoneuro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Prorefugee_Dictionary {
            get {
                return ResourceManager.GetString("Prorefugee_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Prosocial
        ///%
        ///accepting	1
        ///accomodat*	1
        ///affect*	1
        ///agreeable*	1
        ///aid*	1
        ///altruis*	1
        ///appreciat*	1
        ///approachable	1
        ///assist*	1
        ///benefit*	1
        ///benevolen*	1
        ///biodivers*	1
        ///care	1
        ///caring	1
        ///charit*	1
        ///collective*	1
        ///commun*	1
        ///compassion*	1
        ///compliment	1
        ///concern*	1
        ///confide	1
        ///conscien*	1
        ///conservation*	1
        ///considerate	1
        ///contribut*	1
        ///cooperat*	1
        ///cope*	1
        ///coping	1
        ///courteous*	1
        ///courtesy	1
        ///defend*	1
        ///dependab*	1
        ///dignity	1
        ///donat*	1
        ///earth	1
        ///ecolog*	1
        ///education*	1
        ///egalitar*	1
        ///empath*	1
        ///empower*	1
        ///e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Prosocial_Dictionary {
            get {
                return ResourceManager.GetString("Prosocial_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Psychodynamic_Conflict
        ///%
        ///Conflict*	1
        ///Attachment*	1
        ///Deficit*	1
        ///Interpersonal*	1
        ///Intersubjective*	1
        ///Relational*	1
        ///Dissociative*	1
        ///Unconscious*	1
        ///Defense*	1
        ///Id	1
        ///Ego*	1
        ///Superego*	1
        ///Drive*	1
        ///Repress*	1.
        /// </summary>
        internal static string PsychodynamicConflict {
            get {
                return ResourceManager.GetString("PsychodynamicConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Primary_Proc
        ///2	Need
        ///3	Sensation
        ///4	Defensive_Symb
        ///5	Regressive_Cog
        ///6	Icarian_Im
        ///7	Orality
        ///8	Anality
        ///9	Sex
        ///10	Touch
        ///11	Taste
        ///12	Odor
        ///13	Gen_Sensation
        ///14	Sound
        ///15	Vision
        ///16	Cold
        ///17	Hard
        ///18	Soft
        ///19	Passivity
        ///20	Voyage
        ///21	Random_Mvmnt
        ///22	Diffusion
        ///23	Chaos
        ///24	Unknown
        ///25	Timelessness
        ///26	Consc_Alter
        ///27	Brink_Passage
        ///28	Narcissism
        ///29	Concreteness
        ///30	Ascend
        ///31	Height
        ///32	Descent
        ///33	Depth
        ///34	Fire
        ///35	Water
        ///36	Secondary
        ///37	Abstract_Thght
        ///38	Social_Bhvr
        ///39	Instr_Bhvr
        ///40	Restrai [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Regressive_Imagery_Dictionary {
            get {
                return ResourceManager.GetString("Regressive_Imagery_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///998	Locomotion
        ///999	Assessment
        ///%
        ///Act*	998
        ///Can&apos;t wait	998
        ///Chang*	998
        ///Dare*	998
        ///Do it	998
        ///Doer*	998
        ///Done	998
        ///Drive*	998
        ///Dynami*	998
        ///Elimin*	998
        ///Fast*	998
        ///Flow*	998
        ///Get*	998
        ///Go	998
        ///Going	998
        ///Hurr*	998
        ///Initiat*	998
        ///Launch*	998
        ///Lead*	998
        ///Make*	998
        ///Mobil*	998
        ///Momentum	998
        ///Motion	998
        ///Mov*	998
        ///Obstacle*	998
        ///Proceed*	998
        ///Quick*	998
        ///Reduc*	998
        ///Reject*	998
        ///Remov*	998
        ///Smooth*	998
        ///Speed*	998
        ///Start*	998
        ///Urg*	998
        ///Accura*	999
        ///Alternat*	999
        ///Assess*	999
        ///Calculat*	999
        ///Careful*	999
        ///C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Regulatory_Mode_Kanze_Conley_Higgins {
            get {
                return ResourceManager.GetString("Regulatory_Mode_Kanze_Conley_Higgins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	SelfDirection
        ///2	Stimulation
        ///3	Hedonism
        ///4	Achievement
        ///5	Power
        ///6	Security
        ///7	Tradition
        ///8	Conformity
        ///9	Benevolence
        ///10	Universalism
        ///%
        ///#equality	10
        ///#equalpay	10
        ///#equalpayday	10
        ///#fairshot	10
        ///#marriageequality	10
        ///#paycheckfairness	10
        ///#womensucceed	10
        ///abide	1	8
        ///abided	8
        ///abides	8
        ///abiding	8
        ///ability	1
        ///abuse	6
        ///abused	6
        ///abuses	6
        ///abusing	6
        ///accept	10
        ///acceptance	10
        ///accepted	10
        ///accepting	10
        ///accepts	10
        ///accommodate	8
        ///accommodated	8
        ///accommodates	8
        ///accommodating	8
        ///accommodation	8
        ///accommo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SchwartzValuesDict {
            get {
                return ResourceManager.GetString("SchwartzValuesDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Autonomous
        ///2	Controlling
        ///%
        ///choice	1
        ///choose	1
        ///chosen	1
        ///chose	1
        ///alternative	1
        ///option	1
        ///could	1
        ///might	1
        ///which	1
        ///may	1
        ///decision	1
        ///opportunity	1
        ///prefer*	1
        ///select*	1
        ///range	1
        ///free*	1
        ///liberty	1
        ///independ*	1
        ///autonom*	1
        ///made	2
        ///ought	2
        ///obliged	2
        ///have to	2
        ///got to	2
        ///must*	2
        ///should	2
        ///restrict*	2
        ///control*	2
        ///can&apos;t	2
        ///don&apos;t	2
        ///forced	2
        ///unnatural	2
        ///inhibit*	2
        ///repress*	2
        ///held	2
        ///.
        /// </summary>
        internal static string SDTheory_Dictionary {
            get {
                return ResourceManager.GetString("SDTheory_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Security
        ///%
        ///abatement	1
        ///ABMT	1
        ///ghraib	1
        ///afghanistan	1
        ///aggression	1
        ///airland	1
        ///airpower	1
        ///alliance	1
        ///alert	1
        ///alqaeda	1
        ///ammunition	1
        ///amphibious	1
        ///anarchy	1
        ///antipersonnel	1
        ///APT	1
        ///arab	1
        ///arm*	1
        ///assassi*	1
        ///assault	1
        ///atomic	1
        ///attack*	1
        ///authority	1
        ///Baader	1
        ///balance	1
        ///ballistic	1
        ///battle	1
        ///Bin	1
        ///biological	1
        ///bipolar*	1
        ///blitzkrieg	1
        ///block*	1
        ///bomb*	1
        ///bullet	1
        ///capabilit*	1
        ///capitulat*	1
        ///casualt*	1
        ///catastroph*	1
        ///ceasefire	1
        ///chechnya	1
        ///chemical	1
        ///clos*	1
        ///cluster	1
        ///coerc*	1
        ///c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Security_Lexicon {
            get {
                return ResourceManager.GetString("Security_Lexicon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	SelfCare
        ///%
        ///adherence	1
        ///adhere	1
        ///adhering	1
        ///comply	1
        ///heed	1
        ///follow	1
        ///maintain	1
        ///abide	1
        ///obey	1
        ///practice	1
        ///attached	1
        ///devoted	1
        ///salvage	1
        ///HAART	1
        ///SSRI	1
        ///NRTI	1
        ///exercise	1
        ///sustain	1
        ///prolong	1
        ///cleansing	1
        ///progressing	1
        ///helping	1
        ///accordingly	1
        ///guideline	1
        ///reliance	1
        ///diet	1
        ///boost	1
        ///workout	1
        ///affecting	1
        ///tolerable	1
        ///metabolism	1
        ///protected	1
        ///vitamins	1
        ///Vitamins	1
        ///vitamin	1
        ///yoga	1.
        /// </summary>
        internal static string Self_Care_Dictionary {
            get {
                return ResourceManager.GetString("Self_Care_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	PhysSensations
        ///%
        ///achy	1
        ///airy	1
        ///bloated	1
        ///boiling	1
        ///breathless	1
        ///bruised	1
        ///burning	1
        ///bursting	1
        ///butterflies	1
        ///buzzy	1
        ///clammed	1
        ///clenched	1
        ///cold	1
        ///congested	1
        ///constricted	1
        ///contracted	1
        ///dehydrated	1
        ///disconnected	1
        ///dizzy	1
        ///dry-mouthed	1
        ///electric	1
        ///energetic	1
        ///energized	1
        ///faint	1
        ///flexible	1
        ///fluttery	1
        ///frozen	1
        ///full	1
        ///grounded	1
        ///hard	1
        ///headachey	1
        ///heavy	1
        ///hot	1
        ///hungry	1
        ///hurting	1
        ///icy	1
        ///itchy	1
        ///jabbing	1
        ///jittery	1
        ///jumpy	1
        ///knotted	1
        ///light	1
        ///lightheaded	1
        ///limp	1
        ///lo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Shaffer_et_al_2021___Physiological_Sensations {
            get {
                return ResourceManager.GetString("Shaffer_et_al_2021___Physiological_Sensations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///500	Duty
        ///501	Intellect
        ///502	Adversity
        ///503	Mating
        ///504	Positivity
        ///505	Negativity
        ///506	Deception
        ///507	Sociality
        ///%
        ///Achiev*	500
        ///Ambit*	500
        ///Assign	500
        ///Assignment	500
        ///Business*	500
        ///Career*	500
        ///Chore*	500
        ///Chores*	500
        ///Detail*	500
        ///Dut*	500
        ///Effort*	500
        ///Endeavor*	500
        ///Errand*	500
        ///Grind*	500
        ///Homework	500
        ///Industr*	500
        ///Job*	500
        ///Labor*	500
        ///Office*	500
        ///Perform*	500
        ///Practic*	500
        ///Procrastinat*	500
        ///Produc*	500
        ///Profess*	500
        ///Responsib*	500
        ///Task*	500
        ///Trade	500
        ///Trading	500
        ///Work*	500
        ///commit*	500 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Situational8 {
            get {
                return ResourceManager.GetString("Situational8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	SocialTies
        ///%
        ///aunt*	1
        ///boss	1
        ///boyfriend*	1
        ///brother*	1
        ///bud	1
        ///buddies	1
        ///buddy	1
        ///buds	1
        ///child	1
        ///children	1
        ///church	1
        ///churchgoer*	1
        ///club*	1
        ///colleague*	1
        ///companion	1
        ///comrade	1
        ///congregation	1
        ///cousin*	1
        ///crew	1
        ///dad*	1
        ///daughter*	1
        ///employee*	1
        ///employer	1
        ///exgirl*	1
        ///faction	1
        ///father*	1
        ///fellow*	1
        ///fiance*	1
        ///folks	1
        ///fraternit*	1
        ///friend	1
        ///friends*	1
        ///gang	1
        ///girlfriend*	1
        ///grandchil*	1
        ///granddad*	1
        ///granddau*	1
        ///grandf*	1
        ///grandm*	1
        ///grandpa*	1
        ///grandson*	1
        ///great-*	1
        ///husband*	1
        ///kin	1
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Social_Ties_Dictionary {
            get {
                return ResourceManager.GetString("Social_Ties_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Power
        ///2	Achievement
        ///3	Hedonism
        ///4	Stimulation
        ///5	SelfDirection
        ///6	Universalism
        ///7	Benevolence
        ///8	Tradition
        ///9	Conformity
        ///10	Security
        ///%
        ///power	1
        ///strength	1
        ///control	1
        ///achievement	2
        ///ambition	2
        ///success	2
        ///luxury	3
        ///pleasure	3
        ///delight	3
        ///excitement	4
        ///novelty	4
        ///thrill	4
        ///independence	5
        ///freedom	5
        ///liberty	5
        ///unity	6
        ///justice	6
        ///equality	6
        ///kindness	7
        ///charity	7
        ///mercy	7
        ///tradition	8
        ///custom	8
        ///respect	8
        ///restraint	9
        ///regard	9
        ///consideration	9
        ///security	10
        ///safety	10
        ///protection	10.
        /// </summary>
        internal static string ValueLexiconBardi {
            get {
                return ResourceManager.GetString("ValueLexiconBardi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Autonomy
        ///2	Creativity
        ///3	Emotion
        ///4	Moral
        ///5	Cognition
        ///6	Future
        ///7	Thinking
        ///8	Security
        ///9	Inner_Peace
        ///10	Order
        ///11	Justice
        ///12	Advice
        ///13	Career
        ///14	Achievement
        ///15	Wealth
        ///16	Health
        ///17	Learning
        ///18	Nature
        ///19	Animals
        ///20	Purpose
        ///21	Responsible
        ///22	Hard_Work
        ///23	Work_Ethic
        ///24	Perseverance
        ///25	Feeling_Good
        ///26	Forgiving
        ///27	Accepting_Others
        ///28	Helping_Others
        ///29	Gratitude
        ///30	Dedication
        ///31	Self_Confidence
        ///32	Optimisim
        ///33	Honesty
        ///34	Truth
        ///35	Spirituality
        ///36	Religion
        ///37	Significant_Other
        ///3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValuesLexiconWilson {
            get {
                return ResourceManager.GetString("ValuesLexiconWilson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Stress
        ///%
        ///abandon*	1
        ///abuse*	1
        ///ache*	1
        ///aching	1
        ///afraid	1
        ///aggravat*	1
        ///agitat*	1
        ///agoniz*	1
        ///agony	1
        ///alarm*	1
        ///anger*	1
        ///anguish*	1
        ///annoy*	1
        ///anxi*	1
        ///apprehens*	1
        ///asshole*	1
        ///attack*	1
        ///awful	1
        ///awkward*	1
        ///bad	1
        ///beaten	1
        ///bitch*	1
        ///bitter*	1
        ///brutal*	1
        ///burden*	1
        ///complain*	1
        ///crap	1
        ///crappy	1
        ///cried	1
        ///cries	1
        ///cruel*	1
        ///crushed	1
        ///cry	1
        ///crying	1
        ///damn*	1
        ///defeat*	1
        ///depress*	1
        ///despair*	1
        ///desperat*	1
        ///destroy*	1
        ///destruct*	1
        ///devastat*	1
        ///difficult*	1
        ///disadvantage*	1
        ///disappoint*	1
        ///disa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Wang_et_al___2016____Stress_Dictionary {
            get {
                return ResourceManager.GetString("Wang_et_al___2016____Stress_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Direction
        ///2	Prosocial
        ///3	Wellbeing
        ///4	Identity
        ///5	Motivation
        ///6	Coherence
        ///7	Significance
        ///8	Spiritual
        ///9	Socialconnect
        ///10	Purpose
        ///11	Meaning
        ///%
        ///Accomp*	1	5	6	7	10
        ///Achiev*	1	5	7	10
        ///Affect	2	5	7	10	11
        ///Ambitio*	1	5	7	10
        ///Belie*	4	6	7	8	10	11
        ///Career		1	3	4	5	7	9	10	11
        ///Coherence	11
        ///Connect*	10	11
        ///Content	3	4	5	7	10	11
        ///Contribut*	1	2	5	7	9	10	11
        ///Direction	1	5	10
        ///Dream*	1	4	5	6	8	9	10
        ///Effect*		2	5	7	10
        ///Ethic*	2	5	10		
        ///Experience*	6	7	11
        ///Family		2	4	9	10	11	
        ///Financ*	1	3	5	7	10	11
        ///Friend*	2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Well_being_Dictionary {
            get {
                return ResourceManager.GetString("Well_being_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	WhirlAll
        ///%
        ///pivot*	1
        ///purl*	1
        ///reel*	1
        ///revolve	1
        ///revolves	1
        ///revolved	1
        ///revolving	1
        ///roll*	1
        ///rotat*	1
        ///spin	1
        ///spins	1
        ///spun	1
        ///spinning	1
        ///swirl*	1
        ///turn*	1
        ///twirl*	1
        ///twist*	1
        ///whirl*	1.
        /// </summary>
        internal static string Whirlall_Words {
            get {
                return ResourceManager.GetString("Whirlall_Words", resourceCulture);
            }
        }
    }
}
